name       : hyphen
version    : 2.8.8
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/hunspell/Hyphen/2.8/hyphen-2.8.8.tar.gz : 304636d4eccd81a14b6914d07b84c79ebb815288c76fe027b9ebff6ff24d5705
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : programming.library
summary    : hyphenation library to use converted TeX hyphenation patterns
description: |
    hyphenation library to use converted TeX hyphenation patterns
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
