name       : hyphen
version    : 2.8.8
release    : 3
source     :
    - https://altushost-swe.dl.sourceforge.net/project/hunspell/Hyphen/2.8/hyphen-2.8.8.tar.gz : 304636d4eccd81a14b6914d07b84c79ebb815288c76fe027b9ebff6ff24d5705
homepage   : https://hunspell.github.io/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  :
    - programming.library
    - en : office
summary    :
    - hyphenation library to use converted TeX hyphenation patterns
    - en : English hyphenation rules
description: |
    hyphenation library to use converted TeX hyphenation patterns.
patterns   :
    - en : /usr/share/hyphen
rundeps    :
    - en : hyphen
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    pushd $installdir/usr/share/hyphen/
        en_US_aliases="en_AG en_AU en_BS en_BW en_BZ en_CA en_DK en_GB en_GH en_HK en_IE en_IN en_JM en_MW en_NA en_NZ en_PH en_SG en_TT en_ZA en_ZM en_ZW"
        for lang in $en_US_aliases; do
            ln -s hyph_en_US.dic hyph_$lang.dic
        done
    popd
check      : |
    %make check
